spring.jpa:
  database: POSTGRESQL
  show-sql: true

spring.datasource:
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5432/
  username:
  password:

spring:
  flyway:
    enabled: true