spring.jpa:
  database: POSTGRESQL
  show-sql: true

spring.datasource:
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5432/inobitec
  username: insomehead
  password: 3669

spring:
  flyway:
    enabled: true